name: Workflow for Codecov integration
on: [push, pull_request]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          cache: false

      - name: Download dependencies
        run: go mod download

      - name: Test and generate coverage report
        run: make unit_test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0 # https://github.com/codecov/codecov-action
        with:
          file: .build/cover.out
          exclude: ./
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cadence-workflow/cadence-go-client
